version: '3'
services:
  db:
    build:
      dockerfile: Dockerfile.db
      context: .
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      dockerfile: Dockerfile.web
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    depends_on:
      - db
