version: 2.1
orbs:
  ruby: circleci/ruby@1.7.1
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.5-node
    working_directory: ~/fp-dot-com/src
    steps:
      - checkout:
          path: ~/fp-dot-com
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:2.7.5-node
      - image: cimg/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/fp-dot-com/src
    steps:
      - checkout:
          path: ~/fp-dot-com
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: webpack
          command: bundle exec bin/webpack
      - run:
          name: Rspec
          command: bundle exec rspec
  heroku-deploy:
    docker:
      - image: cimg/ruby:2.7.5-node
    working_directory: ~/fp-dot-com/src
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - heroku/deploy-via-git:
          force: true
      - heroku/push-docker-image:
          recursive: true
      - heroku/release-docker-image
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - heroku-deploy:
          requires:
            - test
          filters:
            branches:
              only: master
